# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: switch.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cswitch.proto\",\n\x14SwitchStatusResponse\x12\x14\n\x0cswitch_state\x18\x01 \x01(\t\"&\n\x11LedControlRequest\x12\x11\n\tled_state\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'switch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SWITCHSTATUSRESPONSE']._serialized_start=16
  _globals['_SWITCHSTATUSRESPONSE']._serialized_end=60
  _globals['_LEDCONTROLREQUEST']._serialized_start=62
  _globals['_LEDCONTROLREQUEST']._serialized_end=100
# @@protoc_insertion_point(module_scope)
